In [8]:
import numpy as np

In [11]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [13]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [15]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [16]:
test_cov = a_centered_sp / (a.shape[0] - 1)
test_cov

2.0

**Задание 4****
*Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.*


In [17]:
cov = np.cov(a.T)[0, 1]
cov

2.0

## Тема “Работа с данными в Pandas”
#### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].



In [18]:
import pandas as pd

In [19]:
authors = pd.DataFrame({'author_id' : [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [20]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3], 
                     'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                                 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [21]:
authors_price = pd.merge(authors, book, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [22]:
top5 = authors_price.sort_values(by="price", ascending=False, inplace=False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [23]:
top5_1 = authors_price.nlargest(5, 'price')
top5_1

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [24]:
authors_price 

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [49]:
authors_stat = authors_price.groupby('author_name').agg({'price': 'max'})
authors_stat

price
author_name       
Островский     370
Тургенев       450
Чехов          500

In [47]:
authors_stat = authors_price.groupby('author_name').agg({'price': 'min'})
authors_stat

price
author_name       
Островский     290
Тургенев       300
Чехов          450

In [48]:
authors_stat = authors_price.groupby('author_name').agg({'price': 'mean'})
authors_stat

price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [60]:
authors_stat = authors_price.groupby("author_name").agg({"price": ["max", "min", "mean"]})
authors_stat

price                 
              max  min        mean
author_name                       
Островский    370  290  330.000000
Тургенев      450  300  366.666667
Чехов         500  450  475.000000

In [39]:
authors_stat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Тургенев to Островский
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   author_name  3 non-null      object 
 1   min_price    3 non-null      int64  
 2   max_price    3 non-null      int64  
 3   mean_price   3 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 120.0+ bytes
